baseURL = 'https://blog.cosmic.ovh/'
defaultContentLanguage = 'fr'
title = 'Cosmic Explorator'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[build]
  noJSConfigInAssets = true

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML']

[sitemap]
  changefreq = 'monthly'
  priority = 0.5

[params]
  author = 'Emmanuel B'
  description = 'Notes techniques autour de l’astronomie, de la domotique et de l’informatique.'

[languages]
  [languages.fr]
    locale = 'fr-FR'
    label = 'Français'
    weight = 1

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
