baseURL = 'https://blog.cosmic.ovh/'
defaultContentLanguage = 'fr'
title = 'Cosmic Explorator'
theme = 'aafu'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']
ignoreFiles = ['themes/aafu/content/.*']

[build]
  noJSConfigInAssets = true
  writeStats = true

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML']

[sitemap]
  changefreq = 'monthly'
  priority = 0.5

[params]
  author = 'Emmanuel B'
  description = 'Notes techniques autour de l’astronomie, de la domotique et de l’informatique.'
  copyright = '© Emmanuel B · Propulsé par [Hugo](https://gohugo.io/)'

  [params.theme]
    mainTheme = 'dark'
    showAttribute = true
    singlePage = false

[languages]
  [languages.fr]
    locale = 'fr-FR'
    label = 'Français'
    weight = 1

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
