send:
  name: Envoyer un SMS
  fields:
    phone_number:
      name: Numéro de téléphone
      required: true
      selector:
        text:
    message:
      name: Message
      required: true
      selector:
        text:
          multiline: true

delete:
  name: Supprimer un SMS
  fields:
    message_id:
      name: Identifiant du SMS
      required: true
      selector:
        number:
          min: 0
          mode: box

delete_all:
  name: Supprimer tous les SMS

add_contact:
  name: Ajouter un contact SIM
  fields:
    name:
      name: Nom
      required: true
      selector:
        text:
    phone_number:
      name: Numéro de téléphone
      required: true
      selector:
        text:

delete_contact:
  name: Supprimer un contact
  fields:
    contact_id:
      name: Identifiant du contact
      required: true
      selector:
        number:
          min: 0
          mode: box
